name: Publish Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: Production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env file for docker
        run: |
          echo "NODE_ENV=production" >> .env
          echo "NEXT_PUBLIC_BACKEND_URL=${{secrets.NEXT_PUBLIC_BACKEND_URL}}" >> .env

      - name: Login to docker hub
        run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin

      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg NEXT_PUBLIC_BACKEND_URL=${{secrets.NEXT_PUBLIC_BACKEND_URL}} --tag ${{secrets.DOCKERHUB_USERNAME}}/ocean-harbor-frontend:latest

      - name: Push Docker Image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/ocean-harbor-frontend:latest
